name: moove
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mysql1: ^0.20.0
  http: ^0.13.5
  cupertino_icons: ^1.0.5
  # location: ^5.0.3
  # google_maps_flutter: ^2.5.0
  flutter_local_notifications: ^15.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  permission_handler: ^10.4.1
  intl: ^0.18.1
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.0
  local_auth: ^2.1.6
  geolocator: ^9.0.2
  share: ^2.0.4
  url_launcher: ^6.1.11
  material: ^1.0.0
  flutter_lints: ^1.0.0
  image_picker: ^0.8.4+4
  logger: ^1.1.0
  connectivity: ^3.0.6
  dio: ^4.0.4
  maps_launcher: ^2.2.0
  in_app_update: ^4.2.0
  timezone: ^0.9.2
  image: ^4.0.17
  fl_chart: ^0.63.0
  webview_flutter: ^4.2.4
  encrypt: ^5.0.0
  

flutter:
  assets:
    - assets/imagens/
    
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
